
export const SHOWLOADING = 'SHOWLOADING'
export const HIDELOADING = 'HIDELOADING'
export const EMPLOYEELIST = 'EMPLOYEELIST'
export const EMPLOYEADDEDSUCESS = 'EMPLOYEADDEDSUCESS'
export const EMPLOYEDELETESUCESS = 'EMPLOYEDELETESUCESS'